dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install pylint pycodestyle pydocstyle
script:
  - pylint strider && pycodestyle strider && pydocstyle strider