version: '3'
services:
  neo4j:
    container_name: strider_neo4j
    image: neo4j:3.5.4
    environment:
      - NEO4J_AUTH=none
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - ./neo4j_plugins/:/var/lib/neo4j/plugins/

  rabbitmq:
    container_name: strider_rabbitmq
    image: rabbitmq:3.7.5-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - '5672:5672'
      - '15672:15672'
  
  strider:
    container_name: strider
    image: strider
    build:
      context: .
    environment:
      - NEO4J_HOST=strider_neo4j
      - RABBITMQ_HOST=strider_rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - KPREGISTRY_URL=${KPREGISTRY_URL}
      - BIOLINK_URL=${BIOLINK_URL}
      - OMNICORP_URL=${OMNICORP_URL}
    volumes:
      - ./logs:/home/murphy/logs
    ports:
      - '5781:5781'